//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP3.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S4ByH61LYnDg8zCdXqiUagbAHtozQoemapq+UZnCF/we1DNpNYhsRGk+4jPfdEYwl/+i3BYnPUkZ3oo8k4RCuEznfXyaCwNDEsYSeCcxAt1X53wHTPHoQq7odaLymkRin15s4I7qAXplRybqBg+0T217Y2N0tbldDl9FPxoQm1+c1uhZ6NF3QWCAkjluGMWKIRK1OR3YZexOy1azT+30dXFmi49qMcvCsXdHDPUWoA9jCYPKzsYjHlz++p0XZhHYXA9Q4zeqrmbCzWuyjqZr0f57s1RMXLE+7Xj1ULSRKRFX/V7tqBacDfBUKVEOZXPA6WtmazTJ+unY+OuEu4pChdQWCD0JOrirhjUQ9Ps9LbCBSStnZL5OXQKeUSqRuaEIaC7Z6cLCn2sUv+O0HbI3543b+Vhob6ILE3iVEOohCg4j2amQZk3i57JDjxQRpnsn+l8209d49L3YSvnccbPfq7FGSkmSpTl9LdnDiW+NVVcsE4nc+ZRvSv/4YAkeJO/g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
            set
            {

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TzBDxUWToQR+5mA20suU226/cjq5Jo7Bmv8WkflpMI6Os+EhDe2OiR18V+fVeYPXSejudvH4+ivhS/R/Owf1B9H3V8fcJqb7g+JkjWVQ2L5z/nDMJMgR2ubOWYLTHL7Jr78CBARnjEVctl/TIusA1Q/YgegCry6RySwfzLFfoqHBgLFqmsSC3UZZy/le0b8mcFcKQ+ODIw6rAPvTpBTn0AnGi2roBpM8MyhjQNpT1lZrkI5BIIReb2VsHTsrqE6TPUQIFFa+4yL0B+y01x6U8oqxdQgEWP4tENosYUFA2AESqI+LmJyf8/IvJ/i//BM8AFIwf1ur3yx1FWDBlED8atJAKEN7uMPygSf+VwAO9mWHz5umHEk8MWttm142WmcmXy/n0OMSBrNtiBlgbBR4pBs81+C8KZtZE0XbdpFk889Wva5KVFRFHyjvw70100MQuG4LYrgoVi/JHHvlQ6HWBhcIGwrvhyyHW31zMMIapnylBLiBwlHuGMJNZPTgiYuB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
            set
            {

            }
        }
    }
}
